-- Run this file in Supabase SQL Editor.

CREATE TABLE equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_name TEXT NOT NULL,
    category TEXT NOT NULL,
    asset_code TEXT UNIQUE NOT NULL,
    condition TEXT DEFAULT 'Good',
    availability TEXT DEFAULT 'Available',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT equipment_condition_check
      CHECK (condition IN ('Good', 'Fair', 'For Repair')),
    CONSTRAINT equipment_availability_check
      CHECK (availability IN ('Available', 'Borrowed'))
);

CREATE TABLE borrow_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT REFERENCES equipment(id) ON DELETE RESTRICT,
    borrower_name TEXT NOT NULL,
    borrower_type TEXT NOT NULL,
    department TEXT NOT NULL,
    date_borrowed DATE DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL,
    date_returned DATE,
    status TEXT DEFAULT 'Borrowed',
    user_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT borrower_type_check
      CHECK (borrower_type IN ('Student', 'Faculty', 'Staff')),
    CONSTRAINT transaction_status_check
      CHECK (status IN ('Borrowed', 'Returned', 'Overdue')),
    CONSTRAINT due_date_check
      CHECK (due_date >= date_borrowed)
);

ALTER TABLE equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE borrow_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view equipment"
ON equipment FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can add equipment"
ON equipment FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update equipment"
ON equipment FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated users can delete equipment"
ON equipment FOR DELETE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view transactions"
ON borrow_transactions FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can create transactions"
ON borrow_transactions FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update transactions"
ON borrow_transactions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated users can delete transactions"
ON borrow_transactions FOR DELETE TO authenticated USING (true);

INSERT INTO equipment
(equipment_name, category, asset_code, condition, availability)
VALUES
('Epson Projector', 'Projector', 'PROJ-001', 'Good', 'Available'),
('Acer Laptop', 'Laptop', 'LAP-002', 'Good', 'Available'),
('Canon Camera', 'Camera', 'CAM-003', 'Fair', 'Available'),
('Wireless Microphone', 'Microphone', 'MIC-004', 'Good', 'Available'),
('TP-Link Router', 'Router', 'ROU-005', 'Good', 'Available'),
('HDMI Cable', 'HDMI Cable', 'HDMI-006', 'Good', 'Available'),
('Computer Toolkit', 'Computer Toolkit', 'TOOL-007', 'Good', 'Available'),
('Portable Speaker', 'Portable Speaker', 'SPK-008', 'Good', 'Available');
